name: linux build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get micro-manager 2
        run: git clone https://github.com/micro-manager/micro-manager
      - name: install comedilib
        run: sudo apt-get install libcomedi-dev
      - name: configure
        run: mkdir build && cd build && cmake .. -DMMROOT=micro-manager
      - name: build
        run: cd build && cmake --build .