name: windows build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout local
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cd build && cmake --build .
